### ISSUE TITLE
Requesting code review before moving to kiwi

### ISSUE THREAD

**Issue by sleberknight** [sleberknight/ansible-vault-experimental#45]
_NOTE: This should be done once the two PRs are merged_ (#42 and #44)

I have a couple of things to revisit, but wanted to get your thoughts on the current state before moving this into kiwi.

My own list:

1. The `XxxCommand` factory methods, e.g. `VaultEncryptCommand.from(config, plainTextFilePath)` have the `VaultConfiguration` argument _first_, whereas the `VaultEncryptionHelper` methods such as `encryptFile` have it _last_. Should I change one or the other so they are consistent?
1. Should I add more argument validation to the `XxxCommand` classes and/or the `VaultEncryptionHelper`?
1. Would it be at all useful to have a separate "static utility" class, e.g. `VaultEncryptions` which has `static` methods that are basically what are now in `VaultEncryptionHelper`, and then change `VaultEncryptionHelper` to accept a `VaultConfiguration` which would then be used for each call, and we could remove the `VaultConfiguration` argument from every method. The downside is if you (for some reason) need to change the configuration you'd need to create a new instance).
1. Does it make sense to add an `execute` method to the `OsCommand` interface so that the various commands can be directly executed? They would probably need to return a `Process` object since the actual commands behave differently, e.g. `encryptString` (in `VaultEncryptionHelper`) returns the encrypted `String` whereas `encryptFile` returns the encrypted file `Path`. The main downside that I see is that, in order to facilitate easy testing, we would need to have a `ProcessHelper` argument, i.e. `execute(ProcessHelper)`. Otherwise it would be difficult to test unless each command allowed a `ProcessHelper` to be set on the builder and/or the factory methods, which would make the factory method APIs less clean.

**Comment by terezivy** [comment]
1. Yes, for consistency, I would put the vault configuration to the first position, given its importance.
2. Yes, at the very least that the all the files are present, specifically the key file. Ansible fails silently if any of those files are not present...which we found out the hard way.
3. Yeah the static utility would be a good way to go. As for the need to create a new one when the configuration changes, that is a rare occasion I would think. 
4. Let me think on this one little bit, but my first instinct is yes, add the execute method.

**Comment by sleberknight** [comment]
On item 3. After thinking a bit more on this, the major downside I can see about having any static methods at all is that we won't be able to (practically speaking) mock them. So I'm going back on myself a bit here, since the static methods, if used anywhere, would basically make testing that code impossible.

Instead, maybe an alternative would be to have either:

1. Add a new constructor to `VaultEncryptionHelper`, and add methods that do _not_ take a `VaultConfiguration`
1. Add a second class that takes a `VaultCongfiguration` in its constructor, and basically has the same methods but without a `VaultConfiguration`

The problem with the first option is that class would be confusing, since it would need to throw exceptions if a client calls the "no config arg" methods without having specified a config in the constructor. So that seems like a bad idea.

The problem with the second option is we have almost identical classes.

So maybe a third option is to modify the existing class so the methods _never_ take a config object, _but_ instead you must provide a config in the constructor, _and_ we also permit changing the config via a `changeVaultConfiguration` method or similar setter method. Example usage:

```java
var helper = new VaultEncryptionHelper(vaultConfig);
var encryptedStringVariable = helper.encryptString("the plain text", "varName");

// meanwhile, back at headquarters...
helper.changeVaultConfiguration(newConfig);

String decryptedContents= helper.viewFile(pathToFile);

// ..
```

Or, we just leave the class as is (but change so the config arg is first like the command objects)

**Comment by terezivy** [comment]
I am going to vote for option 3, with the configuration passed in initially and also being able to chagne the config on the rare occasion that it becomes necessary. 👍

**Comment by sleberknight** [comment]
Closing this. Opened issue #46 referencing this issue.
